### PR TITLE
Generates 3 json files, in the "json" directory

### PR DESCRIPTION
**Pull request by rjbou**
- `stats.json` containing: all packages with timestamps, last month all downloads and non-adjacent downloads.
```
  [
    {"name": string <pkg name>,
     "versions":[
        {"version": string <pkg version>,
         "date": string <human readable date: month day, year>,
         "downloads": int <nb dl>,
         "month_downloads": int <nb dl>},
         {"version": ...  }]},
    {"name": ...}
  ]
```
- `last10_updates.json`: last 10 updated packages
```
  [
    {"package": string <pkg>,
     "downloads": int <nb dl>},
    {"package": ... }
  ]
```
- `top10.json`: 10 most popular packages
```
  [
    {"package": string <pkg>,
     "date": string <human readable date: month day, year>},
    {"package": ... }
  ]
```

### CODE REVIEW

**Comment by avsm** [comment]
really handy for ocaml.org, thank you!  Is it possible to factor out the json popularity parser into a separate opam package so ocaml.org can just depend on that? otherwise i can just vendor it, but this way it'll stay in sync.

**Comment by rjbou** [comment]
Yup! It will be the occasion to write one :D
What is implemented in this pr is only the json file generation. They will be reachable via http://opam.ocaml.org/json/<...>.json. A simple curl/wget/aria/you-prefered-way-to-dl-a-file to retrieve it.

**Comment by avsm** [comment]
fantastic; cc @chris00 so he knows the ocaml.org fix is coming :-)

**Comment by Chris00** [comment]
@rjbou Please let us know when the [urls](http://opam.ocaml.org/json/stats.json) will be active.

**Comment by rjbou** [comment]
@Chris00 @avsm 
It was blocked from automatic update because of `yojson` version mismatching. Fixed and deployed!
```
$ cat | curl http://opam.ocaml.org/json/top10.json
[{"package":"graphics.4.07.1","downloads":11899},{"package":"js_of_ocaml.3.4.0","downloads":10718},{"package":"menhir.20181113","downloads":9219},{"package":"merlin.3.2.2","downloads":8716},{"package":"merlin-extend.0.3","downloads":6701},{"package":"cmdliner.1.0.3","downloads":6482},{"package":"lwt.4.2.1","downloads":6391},{"package":"ppx_deriving_yojson.3.3","downloads":5856},{"package":"ppxfind.1.2","downloads":5539},{"package":"cohttp.2.1.2","downloads":5074}]
```

**Comment by rjbou** [comment]
`yosjon` constrained in #172

**Comment by Chris00** [comment]
I have started generating the package list from the json files.  Thanks!

**Pull request merged**
