### PR TITLE
Updates the opam-lib dependency to 1.3

### PR DESCRIPTION
**Pull request by AltGr**

### CODE REVIEW

**Comment by AltGr** [comment]
Needs https://github.com/ocamllabs/opamfu/pull/15 merged first

**Comment by samoht** [comment]
I've merged the other PR and restarted the jobs for this one.

**Comment by samoht** [comment]
@AltGr can you rebase?

Also if you want to test with the unreleased version of opam-lib you can use `PINS=opam-pin.1.3.0:--dev` in the travis file (see the docs in ocaml/ocaml-ci-scripts)

**Comment by AltGr** [comment]
Rebased.

For the opam-lib release, I'd rather wait for opam-lib 1.3.0 to be merged, since this PR makes little sense otherwise anyway.
I also have https://github.com/ocaml/platform-blog/pull/39 on the waiting queue.

Note that this is already in production (at https://opam.ocaml.org) anyway.

**Comment by samoht** [comment]
@AltGr if you have any blocking item please ping me for quick review/merges.

**Comment by avsm** [comment]
needs a rebase after #149

**Comment by Chris00** [comment]
Superseded by https://github.com/ocaml/opam2web/pull/150

**Pull request merged**
