### PR TITLE
port fully to dune

### PR DESCRIPTION
**Pull request by avsm**
I started this to take a look at what else is needed for ocaml.org to use this version, since the ocaml.org build still uses camlp4 (!)

It looks like the `of_repositories` function is missing, so it's probably easier to simplify that in ocaml.org. But this version should already be easier to work with I hope...

### CODE REVIEW

**Comment by avsm** [comment]
cc @chris00 -- just fyi, am refreshing ocaml.org to work with opam2

**Comment by rjbou** [comment]
lgtm!

**Comment by AltGr** [comment]
Thanks!

**Comment by avsm** [comment]
Thanks for the reviews!

**Pull request merged**
